using ExchangeMail.Core.Data.Entities;

namespace ExchangeMail.Core.Services;

public static class SystemRulesSeeder
{
    public static List<MailRuleEntity> GetSystemRules(string userEmail)
    {
        var rules = new List<MailRuleEntity>();
        int priority = 10;

        // 1. Security Alerts
        rules.Add(new MailRuleEntity
        {
            UserEmail = userEmail,
            Name = "Security Alerts",
            Priority = priority++,
            MatchMode = RuleMatchMode.Any,
            IsGlobal = true,
            StopProcessing = false, // Highlight but don't move? "Leave in Inbox and highlight"
            Conditions = new List<MailRuleConditionEntity>
            {
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Verification code" },
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Password reset" },
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Suspicious sign in" }
            },
            Actions = new List<MailRuleActionEntity>
            {
                new() { ActionType = RuleActionType.Flag },
                new() { ActionType = RuleActionType.AddLabel, TargetValue = "Security" }
            }
        });

        // 2. Notifications (GitHub, Azure, Jira)
        rules.Add(new MailRuleEntity
        {
            UserEmail = userEmail,
            Name = "Notifications",
            Priority = priority++,
            MatchMode = RuleMatchMode.Any,
            IsGlobal = true,
            StopProcessing = true,
            Conditions = new List<MailRuleConditionEntity>
            {
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "github.com" },
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "azure.com" },
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "atlassian.net" },
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "noreply" },
                new() { Field = RuleConditionField.IsAutoGenerated, Operator = RuleConditionOperator.Is, Value = "true" }
            },
            Actions = new List<MailRuleActionEntity>
            {
                new() { ActionType = RuleActionType.MoveToFolder, TargetValue = "Notifications" }
            }
        });

        // 3. Mailing Lists
        rules.Add(new MailRuleEntity
        {
            UserEmail = userEmail,
            Name = "Mailing Lists",
            Priority = priority++,
            MatchMode = RuleMatchMode.Any,
            IsGlobal = true,
            StopProcessing = true,
            Conditions = new List<MailRuleConditionEntity>
            {
                new() { Field = RuleConditionField.ListId, Operator = RuleConditionOperator.MatchesRegex, Value = ".+" } // List-Id exists
            },
            Actions = new List<MailRuleActionEntity>
            {
                new() { ActionType = RuleActionType.MoveToFolder, TargetValue = "Mailing Lists" }
            }
        });

        // 4. Marketing
        rules.Add(new MailRuleEntity
        {
            UserEmail = userEmail,
            Name = "Marketing",
            Priority = priority++,
            MatchMode = RuleMatchMode.Any,
            IsGlobal = true,
            StopProcessing = true,
            Conditions = new List<MailRuleConditionEntity>
            {
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "offers@" },
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "promo@" },
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Sale" },
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Discount" }
            },
            Actions = new List<MailRuleActionEntity>
            {
                new() { ActionType = RuleActionType.MoveToFolder, TargetValue = "Marketing" }
            }
        });

        // 5. Transactional / Shopping
        rules.Add(new MailRuleEntity
        {
            UserEmail = userEmail,
            Name = "Shopping",
            Priority = priority++,
            MatchMode = RuleMatchMode.Any,
            IsGlobal = true,
            StopProcessing = true,
            Conditions = new List<MailRuleConditionEntity>
            {
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Order confirmation" },
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Receipt" },
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Invoice" },
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Dispatch" }
            },
            Actions = new List<MailRuleActionEntity>
            {
                new() { ActionType = RuleActionType.MoveToFolder, TargetValue = "Shopping" }
            }
        });

        // 6. Finance
        rules.Add(new MailRuleEntity
        {
            UserEmail = userEmail,
            Name = "Finance",
            Priority = priority++,
            MatchMode = RuleMatchMode.Any,
            IsGlobal = true,
            StopProcessing = true,
            Conditions = new List<MailRuleConditionEntity>
            {
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "bank" }, // Generic
                new() { Field = RuleConditionField.Subject, Operator = RuleConditionOperator.Contains, Value = "Statement" }
            },
            Actions = new List<MailRuleActionEntity>
            {
                new() { ActionType = RuleActionType.MoveToFolder, TargetValue = "Finance" },
                new() { ActionType = RuleActionType.Flag }
            }
        });

        // 7. Social
        rules.Add(new MailRuleEntity
        {
            UserEmail = userEmail,
            Name = "Social",
            Priority = priority++,
            MatchMode = RuleMatchMode.Any,
            IsGlobal = true,
            StopProcessing = true,
            Conditions = new List<MailRuleConditionEntity>
            {
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "facebookmail.com" },
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "linkedin.com" },
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "twitter.com" },
                new() { Field = RuleConditionField.From, Operator = RuleConditionOperator.Contains, Value = "instagram.com" }
            },
            Actions = new List<MailRuleActionEntity>
            {
                new() { ActionType = RuleActionType.MoveToFolder, TargetValue = "Social" }
            }
        });

        return rules;
    }
}
