using System.ComponentModel.DataAnnotations;

namespace ExchangeMail.Core.Data.Entities;

public class UserEntity
{
    [Key]
    public int Id { get; set; }
    public required string Username { get; set; }
    public required string Password { get; set; }
    public bool IsAdmin { get; set; }
    public string? Signature { get; set; }
    public bool EnableAnimations { get; set; }
    public bool EnableAutoLabeling { get; set; }
}

public class MessageEntity
{
    [Key]
    public required string Id { get; set; } // MessageId
    public required string From { get; set; }
    public required string To { get; set; }
    public required string Subject { get; set; }
    public DateTime Date { get; set; }
    public bool IsImported { get; set; }
    public required byte[] RawContent { get; set; }
    public string? MessageIdHeader { get; set; }
    public string? InReplyTo { get; set; }
    public string? ThreadId { get; set; }
}

public enum RuleMatchMode
{
    Any,
    All
}

public enum RuleConditionField
{
    From,
    Subject,
    Body,
    Header,
    SenderInContacts,
    ListId,
    HasAttachment,
    IsAutoGenerated
}

public enum RuleConditionOperator
{
    Contains,
    Equals,
    MatchesRegex,
    Is,
    DoesNotContain,
    StartsWith,
    EndsWith
}

public enum RuleActionType
{
    MoveToFolder,
    MarkAsRead,
    AddLabel,
    Delete,
    StopProcessing,
    Flag
}

public class MailRuleEntity
{
    [Key]
    public int Id { get; set; }
    public required string UserEmail { get; set; }
    public required string Name { get; set; }
    public int Priority { get; set; }
    public RuleMatchMode MatchMode { get; set; }
    public bool IsGlobal { get; set; }
    public bool StopProcessing { get; set; }
    public bool IsEnabled { get; set; } = true;

    // Navigation properties
    public List<MailRuleConditionEntity> Conditions { get; set; } = new();
    public List<MailRuleActionEntity> Actions { get; set; } = new();
}

public class MailRuleConditionEntity
{
    [Key]
    public int Id { get; set; }
    public int RuleId { get; set; }
    public RuleConditionField Field { get; set; }
    public RuleConditionOperator Operator { get; set; }
    public string? Value { get; set; }

    // Navigation
    // public MailRuleEntity Rule { get; set; }
}

public class MailRuleActionEntity
{
    [Key]
    public int Id { get; set; }
    public int RuleId { get; set; }
    public RuleActionType ActionType { get; set; }
    public string? TargetValue { get; set; }

    // Navigation
    // public MailRuleEntity Rule { get; set; }
}

public class ConfigEntity
{
    [Key]
    public required string Key { get; set; }
    public required string Value { get; set; }
}

public class FolderEntity
{
    [Key]
    public int Id { get; set; }
    public required string Name { get; set; }
    public required string UserEmail { get; set; }
}

public class ContactEntity
{
    [Key]
    public int Id { get; set; }
    public required string Name { get; set; }
    public required string Email { get; set; }
    public string? PhoneNumber { get; set; }
    public string? Address { get; set; }
    public string? Notes { get; set; }
}

public class LogEntity
{
    [Key]
    public int Id { get; set; }
    public DateTime Date { get; set; }
    public required string Level { get; set; } // Info, Warning, Error
    public required string Source { get; set; } // SMTP, System, etc.
    public required string Message { get; set; }
    public string? Exception { get; set; }
}
